feat: Task 1.1.3
MargoVI/JBDC-Task-1 pull request #1
Opened 2024-01-11 19:49 UTC by IIMargo

2024-01-11 20:48 UTC, pdasilem requested changes
ошибки те же, что и у твоего коллеги, задачу которого я уже проверил )

2024-01-14 09:00 UTC, pdasilem requested changes
убери папку таргет. она лишняя в пр
и, все-таки, постарайся называть переменные понятными именами. stmt выглядит как ругательство )

2024-01-14 09:00 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/Main.java
> +    private final static UserService userService = new UserServiceImpl();
не надо здесь статику использовать. переделай

2024-01-14 09:35 UTC, IIMargo commented on src/main/java/jm/task/core/jdbc/Main.java
> +    private final static UserService userService = new UserServiceImpl();
сделано)

2024-01-14 10:51 UTC, pdasilem approved these changes

2024-01-14 12:46 UTC, merged